language: php

services:
  - mysql

php:
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/composer

before_script:
  - cp .env.example .env
  - travis_retry composer install --no-interaction --prefer-source
  - if [[ "$DB_DRIVER" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS test;" -U postgres; fi
  - if [[ "$DB_DRIVER" == "pgsql" ]]; then psql -c "create database test;" -U postgres; fi
  - if [[ "$DB_DRIVER" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS test;" -uroot; fi
  - php rotor migrate
  - php rotor seed:run

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --stderr

env:
  global:
    - APP_ENV=testing
    - DB_HOST=127.0.0.1
    - DB_DRIVER=mysql
    - DB_DATABASE=test
    - DB_USERNAME=root
    - DB_PASSWORD=

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
